In [59]:
!pip install numpy

In [60]:
import numpy as np

In [62]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [61]:
# Reshape x with 8 rows and 2 columns
n=x.reshape((4,4)) # 2d
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
2


In [63]:
n1=n.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [64]:
 # convert to old dimension
v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)

(16,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1


In [65]:
# reshape x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
print(x)
x.reshape((2,4,2))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [ ]:
# Flattening x convert array into one dimensional
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [66]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,17,2)

# print a
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [82]:
# Get third element in array a
print(a[1])

[4 5 6]


In [67]:
#Print 1st, 3rd, 5th, and 7th element in array a
a[0:7:2]


array([ 2,  6, 10, 14])

In [68]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# print the 3rd element from the 3rd row of a
print(a[2,0])

7


In [ ]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b.shape
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
print(b[1][0][0])

7


In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Slice elements from index 5 to the end of the array arr:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [ ]:
# Print every other element from index 1 to index 7:
arr[1:7:2]

array([2, 4, 6])

In [ ]:
# Print array a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# In array 'a' print index 2 from all the rows :
# print(a[:, 2])  # This slices all rows (:) and only the 0th column
print(a[0, :])  # First row, all columns

[1 2 3]


In [ ]:
print(a[0:2, 1:3])  # All rows, first two columns

[[2 3]
 [5 6]]


In [56]:
x1= np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# assign x2 = x1
x2 = x1 # view

In [74]:
#print x1 and x2
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [77]:
# change 1st element of x2 as 10
x2[0] = 10

In [79]:
#Again print x1 and x2
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [81]:
print(id(x1))
print(id(x2))

137567986284752
137567986284752


In [84]:
# Check memory share between x1 and x2
print(np.shares_memory(x1, x2))
print(id(x1))
print(id(x2))

True
137567986284752
137567986284752


In [87]:
# Create a view of x1 and store it in x3.
x3 = x1.view()

In [89]:
# Again check memory share between x1 and x3
np.shares_memory(x1, x3)

True

In [92]:
#Change 1st element of x3=100
x3[0] = 100

In [94]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [96]:
# Now create an array x4 which is copy of x1

x4 = np.copy(x1)

In [99]:
# Change the last element of x4 as 900
x4[-1] = 900

In [100]:
# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


In [102]:
#Check memory share between x1 and x4
print(id(x1))
print(id(x4))
np.shares_memory(x1, x4)


137567986284752
137567984901296


False

In [104]:
#print a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
# Check if every element in array a greater than 3 or not Using '>' notation
a > 3


array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [108]:
# Get a list with all elements of array 'a' grater than 3
a[a > 3]

array([4, 5, 6, 7, 8, 9])

In [110]:
# Get a list with all elements of array 'a' greater than 3 but less than 6
a[(a > 2) & (a <= 7)]

array([3, 4, 5, 6, 7])

In [112]:
# check if each elements in array 'x1' equals array 'x4' using '==' notation
x1 == x4
# print(x1)
# print(x4)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [114]:
# Print Transpose of array 'a'
print(a.transpose())
#print array 'a'
print("-----------------")
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
-----------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [116]:
# stack x1 and x4 along columns.
print(x1)
print(x4)
np.vstack((x1, x4))

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100,   1,   2,   3,   4,   5,   6,   7,   8, 900]])

In [117]:
#stack x1 and x4 along rows
np.hstack((x1, x4))

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,   1,   2,
         3,   4,   5,   6,   7,   8, 900])

In [119]:
# Inserts values into array x1 before index 4 with elements of x4
print(x1)
print(x4)
np.insert(x1, 4, x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([100,   1,   2,   3, 100,   1,   2,   3,   4,   5,   6,   7,   8,
       900,   4,   5,   6,   7,   8,   9])

In [121]:
# delete 2nd element from array x2
print(x2)
np.delete(x2, 2)

[100   1   2   3   4   5   6   7   8   9]


array([100,   1,   3,   4,   5,   6,   7,   8,   9])

In [125]:
#defining a
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [127]:
# print trigonometric sin value of each element of a
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [130]:
print(np.sin(0))

0.0


In [132]:
print(np.tan(0))


0.0


In [134]:
print((np.sin(a))/(np.cos(a)))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [136]:
# print trigonometric cos value of each element of a
print(np.cos(a))
print(np.tan(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [138]:
# Print exponential value of each elements of a
np.exp(a) # **

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [140]:
# print total sum of elements of a
np.sum(a)

np.int64(45)

In [142]:
# Print sum in array a column wise
np.sum(a, axis=0)

array([12, 15, 18])

In [144]:
# Print sum in array a row wise
np.sum(a, axis=1)


array([ 6, 15, 24])

In [146]:
# print median of array a
print(np.median(a))

5.0


In [148]:
# print mean of array a
print(np.mean(a))


5.0


In [150]:
# print standard deviation of array a
np.std(a)

np.float64(2.581988897471611)

In [152]:
#print largest element present in array a
np.max(a)

np.int64(9)

In [154]:
# print sorted x4 array
np.sort(x4)

array([  1,   2,   3,   4,   5,   6,   7,   8, 100, 900])

In [156]:
# Create a numpy array
arr = np.array([[12,14,17,19,24,27,35,38]])

# Use numpy.where() with 1 Dimensional Arrays
arr1 = np.where(arr > 17)
print(arr1)



(array([0, 0, 0, 0, 0]), array([3, 4, 5, 6, 7]))


In [158]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [160]:
print(dir(set))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [162]:
import keyword
print(keyword.kwlist)
print(len(keyword.kwlist))

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


In [173]:
import numpy as np

# Creating a 2D array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Reshape to a 1D array
reshaped_arr = arr.reshape(9)
print(reshaped_arr)


[1 2 3 4 5 6 7 8 9]


In [166]:
reshape_arr = arr.reshape(1,9)
print(reshape_arr)

[[1 2 3 4 5 6 7 8 9]]


In [168]:
flattern_arr = arr.flatten()
print(flattern_arr)

[1 2 3 4 5 6 7 8 9]


In [175]:
import numpy as np

# Creating a 2D array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6 7 8 9]


In [179]:
flat_arr[0] = 100
print(flat_arr)

[100   2   3   4   5   6   7   8   9]


In [181]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [183]:
ravel_arr = arr.ravel()
ravel_arr[0] = 1001
print(arr)

[[1001    2    3]
 [   4    5    6]
 [   7    8    9]]


In [185]:
print(np.shares_memory(arr,ravel_arr))

True


In [186]:
print(np.shares_memory(x1, x2))

True
