In [ ]:
!pip install numpy

In [3]:
import numpy as np


In [11]:
a = np.array([1,2,3,4,{1:124}])
a


array([1, 2, 3, 4, {1: 124}], dtype=object)

In [13]:
a= np.array(10)
b = np.array([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [16]:
#print dimentions of a,b, c and d
print('a dimension:', a.ndim)
print('b dimension:', b.ndim)
print('c dimension:', c.ndim)
print('d dimension:', d.ndim)

a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3


In [18]:
print(a.dtype)
print(b.dtype)

int64
int64


In [20]:
print(a)
print('shape of a:', a.shape)
print(b)
print('shape of b:', b.shape)
print(c)
print('shape of c:', c.shape)
print(d)
print('shape of d:', d.shape)

10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
shape of d: (2, 2, 3)


In [22]:
print(type(c))
print(type(d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [25]:
len(b)

3

In [27]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [32]:
np.zeros((7,7),dtype='int')

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [34]:
np.ones((7,7),dtype='int')

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [36]:
np.full((7,7),20,dtype='int')

array([[20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20]])

In [39]:
x = [1,2,3,4,5,6,7,8,9]
# len(x)
np.diag(x)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])